apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lb
  namespace: three-tier
  labels:
    name: ingress-lb
spec:
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 80

